services:
  fastapi_server:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8000:8000"

    volumes:
      - ./logs:/app/logs

    restart: always
    container_name: fastapi_server
