name: Run Pytest

on:
    push:
        branches:
            - "**"
    pull_request:

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.12"

            - name: Install Poetry
              run: pip install poetry

            - name: Install dependencies
              run: poetry install --no-root

            - name: Run Pytest
              run: |
                  PYTHONPATH=$(pwd) poetry run pytest --maxfail=5 --disable-warnings --cov=app --cov-report=xml
